apiVersion: v1
kind: Service
metadata:
  name: planner-backend
  namespace: timeplanner
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: planner-backend
  type: ClusterIP
