// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/google/wire"
	"planner-backend/app/controller"
	"planner-backend/config"
)

// Injectors from wire.go:

func BuildInjector() (*config.Injector, func(), error) {
	contextContext := context.Background()
	driverWithContext := config.ConnectToDB(contextContext)
	systemControllerImpl := &controller.SystemControllerImpl{}
	injector := &config.Injector{
		DB:         driverWithContext,
		SystemCtrl: systemControllerImpl,
	}
	return injector, func() {
	}, nil
}

// wire.go:

var db = wire.NewSet(config.ConnectToDB, context.Background)

var InjectorSet = wire.NewSet(wire.Struct(new(config.Injector), "*"))
