// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/google/wire"
	"planner-backend/app/controller"
	"planner-backend/app/repository"
	"planner-backend/app/service"
	"planner-backend/config"
)

// Injectors from wire.go:

func BuildInjector() (*config.Injector, func(), error) {
	contextContext := context.Background()
	driverWithContext := config.ConnectToDB(contextContext)
	systemControllerImpl := &controller.SystemControllerImpl{}
	departmentRepositoryImpl := repository.DepartmentRepositoryInit(driverWithContext)
	departmentServiceImpl := &service.DepartmentServiceImpl{
		DepartmentRepository: departmentRepositoryImpl,
	}
	departmentControllerImpl := &controller.DepartmentControllerImpl{
		DepartmentService: departmentServiceImpl,
	}
	workplaceRepositoryImpl := repository.WorkplaceRepositoryInit(driverWithContext)
	workplaceServiceImpl := &service.WorkplaceServiceImpl{
		WorkplaceRepository: workplaceRepositoryImpl,
	}
	workplaceControllerImpl := &controller.WorkplaceControllerImpl{
		WorkplaceService: workplaceServiceImpl,
	}
	timeslotRepositoryImpl := repository.TimeslotRepositoryInit(driverWithContext)
	timeslotServiceImpl := &service.TimeslotServiceImpl{
		TimeslotRepository: timeslotRepositoryImpl,
	}
	timeslotControllerImpl := &controller.TimeslotControllerImpl{
		TimeslotService: timeslotServiceImpl,
	}
	weekdayRepositoryImpl := repository.WeekdayRepositoryInit(driverWithContext)
	weekdayServiceImpl := &service.WeekdayServiceImpl{
		WeekdayRepository:  weekdayRepositoryImpl,
		TimeslotRepository: timeslotRepositoryImpl,
	}
	weekdayControllerImpl := &controller.WeekdayControllerImpl{
		WeekdayService: weekdayServiceImpl,
	}
	injector := &config.Injector{
		DB:             driverWithContext,
		SystemCtrl:     systemControllerImpl,
		DepartmentCtrl: departmentControllerImpl,
		WorkplaceCtrl:  workplaceControllerImpl,
		TimeslotCtrl:   timeslotControllerImpl,
		WeekdayCtrl:    weekdayControllerImpl,
	}
	return injector, func() {
	}, nil
}

// wire.go:

var db = wire.NewSet(config.ConnectToDB, context.Background)

var InjectorSet = wire.NewSet(wire.Struct(new(config.Injector), "*"))
