apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: planner-backend-db-pvc
  namespace: timeplanner
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
