apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-db
  namespace: timeplanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-db
  template:
    metadata:
      labels:
        app: api-gateway-db
        tier: backend
    spec:
      containers:
        - name: api-gateway-db
          image: postgres:16
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: secrets
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "2Gi"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - api-gateway-db
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - api-gateway-db
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
            # This deployment does not need a volume mount because its just for testing
