version: "3.9"

services:
  app:
    env_file:
      - .env
    image: mcr.microsoft.com/devcontainers/base:jammy
    command: sleep infinity
    depends_on:
      - gateway-db
      - planner-db
    volumes:
      - ../../:/workspaces:cached
    networks:
      - default

  gateway-db:
    env_file:
      - .env
    image: postgres:16
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - gateway-db-data:/var/lib/postgresql/data
    networks:
      - default

  planner-db:
    image: neo4j:community
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - planner-db-data:/data
      - planner-db-log:/logs
    networks:
      - default

volumes:
  planner-db-data:
  planner-db-log:
  gateway-db-data:

networks:
  default:
    name: timeplanner
