version: "3.9"

services:
  app:
    env_file:
      - .env
    image: mcr.microsoft.com/devcontainers/base:jammy
    command: sleep infinity
    depends_on:
      - auth-db
      - planner-db
    volumes:
      - ../../:/workspaces:cached
    networks:
      - default

  auth-db:
    env_file:
      - .env
    image: postgres:16
    restart: unless-stopped
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - default

  planner-db:
    image: neo4j:community
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - planner-db-data:/data
    networks:
      - default

volumes:
  planner-db-data:
  auth-db-data:

networks:
  default:
    name: backend
