// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"auth-backend/app/controller"
	"auth-backend/app/repository"
	"auth-backend/app/service"
	"github.com/google/wire"
)

// Injectors from injector.go:

func Init() *Initialization {
	gormDB := ConnectToDB()
	userRepositoryImpl := repository.UserRepositoryInit(gormDB)
	userServiceImpl := service.UserServiceInit(userRepositoryImpl)
	userControllerImpl := controller.UserControllerInit(userServiceImpl)
	departmentRepositoryImpl := repository.DepartmentRepositoryInit(gormDB)
	departmentServiceImpl := service.DepartmentServiceInit(departmentRepositoryImpl)
	departmentControllerImpl := controller.DepartmentControllerInit(departmentServiceImpl)
	permissionRepositoryImpl := repository.PermissionRepositoryInit(gormDB)
	permissionServiceImpl := service.PermissionServiceInit(permissionRepositoryImpl)
	permissionControllerImpl := controller.PermissionControllerInit(permissionServiceImpl)
	initialization := NewInitialization(userRepositoryImpl, userServiceImpl, userControllerImpl, departmentRepositoryImpl, departmentServiceImpl, departmentControllerImpl, permissionRepositoryImpl, permissionServiceImpl, permissionControllerImpl)
	return initialization
}

// injector.go:

var db = wire.NewSet(ConnectToDB)

/* User */
var userServiceSet = wire.NewSet(service.UserServiceInit, wire.Bind(new(service.UserService), new(*service.UserServiceImpl)))

var userRepoSet = wire.NewSet(repository.UserRepositoryInit, wire.Bind(new(repository.UserRepository), new(*repository.UserRepositoryImpl)))

var userCtrlSet = wire.NewSet(controller.UserControllerInit, wire.Bind(new(controller.UserController), new(*controller.UserControllerImpl)))

/* Department */
var departmentServiceSet = wire.NewSet(service.DepartmentServiceInit, wire.Bind(new(service.DepartmentService), new(*service.DepartmentServiceImpl)))

var departmentRepoSet = wire.NewSet(repository.DepartmentRepositoryInit, wire.Bind(new(repository.DepartmentRepository), new(*repository.DepartmentRepositoryImpl)))

var departmentCtrlSet = wire.NewSet(controller.DepartmentControllerInit, wire.Bind(new(controller.DepartmentController), new(*controller.DepartmentControllerImpl)))

/* Permission */
var permissionServiceSet = wire.NewSet(service.PermissionServiceInit, wire.Bind(new(service.PermissionService), new(*service.PermissionServiceImpl)))

var permissionRepoSet = wire.NewSet(repository.PermissionRepositoryInit, wire.Bind(new(repository.PermissionRepository), new(*repository.PermissionRepositoryImpl)))

var permissionCtrlSet = wire.NewSet(controller.PermissionControllerInit, wire.Bind(new(controller.PermissionController), new(*controller.PermissionControllerImpl)))
